version: "3"

services:
  rossum:
    build: .
    image: rossum_convert:latest

    environment:
      BASIC_AUTH_USERNAME: myUser123
      BASIC_AUTH_PASSWORD: secretSecret
      ROSSUM_DOMAIN: ${ROSSUM_DOMAIN}
      ROSSUM_BEARER_TOKEN: ${ROSSUM_BEARER_TOKEN}
      ROSSUM_USERNAME: ${ROSSUM_USERNAME}
      ROSSUM_PASSWORD: ${ROSSUM_PASSWORD}
      POSTBIN_URL: ${POSTBIN_URL}

    ports:
      - "8080:8080"

    command: poetry run rossum

  test:
    image: curlimages/curl
    depends_on:
      - rossum
    command:
      - /bin/sh
      - -c
      - |
        sleep 5 # ok, this should be smarter...
        curl -u myUser123:secretSecret -H "annotation-id: 3227735" -H "queue-id: 1161196" http://rossum:8080/export

  # Universal docker compose for running any command via poetry
  poetry:
    build:
      dockerfile: Dockerfile
      context: .
    image: rossum_convert:latest
    volumes:
      - ./:/app:z
    entrypoint: poetry
